[package]
name = "unix-udp-sock"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
